### ISSUE TITLE
Getting 401 error when using STOP rest api

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#42] opened 2020-04-25 05:28 UTC
Hi Team,

Getting 401 Error when using STOP rest api, its happening only in 2.13.0 version only. When i rollback to 2.11.0 its working fine.

![image](https://user-images.githubusercontent.com/6995567/80272081-fc7d7500-86e3-11ea-9d7c-11026436e9c6.png)

Used API.
https://docs.openvidu.io/en/2.13.0/reference-docs/REST-API/#post-apirecordingsstopltrecording_idgt

**Comment by pabloFuente** [comment] 2020-04-25 09:26
That's an UNAUTHORIZED response, as you can see in the browser's error. Check your secret in 2.13.0 installation.

**Comment by surya5353** [comment] 2020-04-25 09:32
Yah, Secret key also updated. only problem in stop api, remaining all apis are working fine.

**Comment by pabloFuente** [comment] 2020-04-27 12:00
Okey, please tell me the details of your OpenVidu installation:

- CE or PRO?
- AWS or On Premises?
- Which type of certificate are you using ("selfsigned", "letsencrypt", "owncert")
- What type of recording are you starting and stoping?: recording mode (ALWAYS/MANUAL), recording output (COMPOSED/INDIVIDUAL), streams recorded (AUDIO + VIDEO, AUDIO ONLY, VIDEO ONLY).
- How many streams are being recorded

I'll try to replicate your exact scenario and check if the problem exists. If we cannot replicate the error hten we won't be able to fix it.

Regards.

**Comment by surya5353** [comment] 2020-04-27 12:08
Thanks for your reply.

CE or PRO? : **Pro Version**
AWS or On Premises?: **AWS**
Which type of certificate are you using: **Letencrypt**
What type of recording are you starting and stoping?: **Manual**
recording output: **Composed**


Thank you.

**Comment by surya5353** [comment] 2020-05-04 12:36
Hi,
Still Waiting for your reply. And please let us know when we get 2.13.0 stable release ?

**Comment by pabloFuente** [comment] 2020-05-04 13:26
2.13.0 stable release is already out.

If you can try upgrading to 2.13.0 to see if your problem is solved. What I can tell you is that that stop recording API is working fine in all of our deployments, and no one has ever reported a similar problem. It is very strange, becuasue if this were a real problem, virtually all OpenVidu users would have reported the problem, as it is a very common method to be used.

Come back when upgrading to 2.13.0 to see if the problem is solved, please. You can follow these instructions: https://docs.openvidu.io/en/2.13.0/openvidu-pro/deployment/aws/

**Comment by surya5353** [comment] 2020-05-04 13:34
Thanks for your reply.

Is Screenshare working in Openvidu-insecure-angular or Angular-library ? Or we must use for OpenviduCall  application let me know clarity on that. Because of my current project already developed with openvidu-insecure-angular and angular-library. 

In OpnviduCall how we can implement without docker and  openvidu-call-back folder? we have already server implemented in AWS. Here my question is how to setup openviduCall in localDev with live server url, is it possible without docker ?

**Comment by micaelgallego** [comment] 2020-05-04 21:54
You can use screen share with any application using OpenVidu. OpenVidu Call is one of our demo projects using it, but you can use in any app.

OpenVidu production deployment and development is based on docker. You can install like you want (it is open source), but it is not supported by us.

Regards

**Comment by surya5353** [comment] 2020-05-04 23:38
Thanks for you reply. But screen share works with only 2.13.0 right. Lasttime we discuss with Carlos he said screenshare works in latest vesrion only. Thats what iam asking you.
In openvidu andular library its not working so...


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by CSantosM** [comment] 2020-05-05 06:54
Screen sharing works with all OpenVidu version. 
Simply, in **OpenVidu Call 2.12.0** there is a bug with screen sharing.

As Openvidu Call is a open source project, you can fix it and generate the angular library or wait until the new Openvidu Call version is released. 

Greetings

**Comment by micaelgallego** [comment] 2020-05-05 07:56
OpenVidu 2.14 version, with screen share fix in Angular library, will be released in a few weeks

**Closed** 2020-08-18 11:32 UTC
